name: amd64_windows_clang

on: [push, pull_request]

jobs:
  amd64_windows_clang:
    runs-on: windows-2019
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v2

    - name: Add MSYS2 to PATH
      shell: bash
      run: echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH

    - name: Update pacman and mirrors
      run: |
        pacman -Sy --noconfirm
        pacman -S --noconfirm pacman-mirrors

    - name: Install Clang toolchain and dependencies
      run: pacman --noconfirm -S \
        mingw64/mingw-w64-x86_64-clang \
        mingw64/mingw-w64-x86_64-cmake \
        mingw64/mingw-w64-x86_64-qtwebkit \
        mingw64/mingw-w64-x86_64-python

    - name: Add mingw64 to PATH
      shell: bash
      run: echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH

    - name: Display tools version
      run: |
        clang++ --version
        cmake --version
        qmake --version
        python --version

    - name: Configure PhantomJS
      run: bash ./configure
      env:
        CMAKE_CMD: 'cmake -G "MinGW Makefiles"'

    - name: Build with mingw32-make
      run: mingw32-make

    - name: Inspect built binary
      run: |
        file ./bin/phantomjs || echo "file check failed"
        ldd ./bin/phantomjs || echo "ldd check failed"

    - name: Run PhantomJS
      run: ./bin/phantomjs --version || echo "phantomjs execution failed"
