name: Code Style Check
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install clang-format
      run: sudo apt install -y clang-format
    - name: Run clang-format
      run: bash ./tools/format-code.sh
    - name: Show diff
      run: git diff
    - name: Enforce formatting
      run: git diff --quiet HEAD
