name: Build (Linux GCC)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y g++ cmake libqt5webkit5-dev qtbase5-dev python3

    - name: Show versions
      run: |
        g++ --version
        cmake --version
        qmake --version
        python3 --version

    - name: Configure
      run: ./configure
      env:
        CMAKE_CMD: 'cmake -G "Unix Makefiles"'

    - name: Build
      run: make -j$(nproc)

    - name: Run binary
      run: ./bin/phantomjs --version || echo "phantomjs execution failed"

    - name: Run tests
      run: |
        echo "Running tests..."
        make check || true  # Allow failure for inspection
